name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Checkout composer
        uses: docker://composer

      - name: Checkout PHP
        uses: docker://php:latest

      - name: Run tests
        working-directory: ${{ runner.workspace }}
        run: |
          cd izhevsk && \
          composer install && \
          ./vendor/bin/phpunit
