name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build
        uses: docker://php:latest

      - name: run tests
        run: ./vendor/bin/phpunit
